modLoader="javafml"
loaderVersion="[28,)" #forge version dep
issueTrackerURL="https://github.com/iChun/iChunUtil/issues"

[[mods]]
    modId="ichunutil"
    version="${file.jarVersion}" #mandatory
    displayName="iChunUtil"
    displayURL="https://ichun.me/mods/ichunutil/"
    authors="iChun"
    description='''
    Shared library mod required by most of iChun's Mods.
    If the first version number of the mod is higher than 1, (eg: 2.X.X, 5.Y.Y), and it's an iChun mod, it needs this.
    '''

[[dependencies.betterthanbunnies]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterthanbunnies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
